2023-06-19 12:12:44,094 INFO    MainThread:17023 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-19 12:12:44,094 INFO    MainThread:17023 [wandb_setup.py:_flush():76] Configure stats pid to 17023
2023-06-19 12:12:44,094 INFO    MainThread:17023 [wandb_setup.py:_flush():76] Loading settings from /home/andrea/.config/wandb/settings
2023-06-19 12:12:44,094 INFO    MainThread:17023 [wandb_setup.py:_flush():76] Loading settings from /home/andrea/Documenti/Computer Science/Natural Language Procesing/nlp2023-hw2/wandb/settings
2023-06-19 12:12:44,094 INFO    MainThread:17023 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-19 12:12:44,095 WARNING MainThread:17023 [wandb_setup.py:_flush():76] Could not save program above cwd: /home/andrea/Documents/Computer Science/Natural Language Procesing/nlp2023-hw2/train_model.py
2023-06-19 12:12:44,095 INFO    MainThread:17023 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '/home/andrea/Documents/Computer Science/Natural Language Procesing/nlp2023-hw2/train_model.py'}
2023-06-19 12:12:44,095 INFO    MainThread:17023 [wandb_init.py:_log_setup():507] Logging user logs to ./wandb/run-20230619_121244-ahyhfhrj/logs/debug.log
2023-06-19 12:12:44,095 INFO    MainThread:17023 [wandb_init.py:_log_setup():508] Logging internal logs to ./wandb/run-20230619_121244-ahyhfhrj/logs/debug-internal.log
2023-06-19 12:12:44,095 INFO    MainThread:17023 [wandb_init.py:init():547] calling init triggers
2023-06-19 12:12:44,095 INFO    MainThread:17023 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-06-19 12:12:44,095 INFO    MainThread:17023 [wandb_init.py:init():596] starting backend
2023-06-19 12:12:44,095 INFO    MainThread:17023 [wandb_init.py:init():600] setting up manager
2023-06-19 12:12:44,099 INFO    MainThread:17023 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-19 12:12:44,104 INFO    MainThread:17023 [wandb_init.py:init():606] backend started and connected
2023-06-19 12:12:44,108 INFO    MainThread:17023 [wandb_init.py:init():703] updated telemetry
2023-06-19 12:12:44,130 INFO    MainThread:17023 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-06-19 12:12:44,645 ERROR   MainThread:17023 [wandb_init.py:init():762] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-06-19 12:12:44,735 ERROR   MainThread:17023 [wandb_init.py:init():1170] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/home/andrea/miniconda3/envs/nlp2023-hw2/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 768, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
